### ISSUE TITLE
It’s unstable when writing with pencil tool.

### ISSUE THREAD

**Issue by HerissonDigital** [antonlorani/jottre#7]
That’s the best simple note taking app, well, that was the best.. It changed recently. I really love the app, but for about 5-6 months, it’s quite shaky with the interface. It keeps juggling and the tools are not acting precisely within the app. And it’s suuuper laggy. It definitely wasn’t that way before. I don’t know, maybe it can be related to iOS 16. 

Is there any hope?

**Comment by antonlorani** [comment]
Hi there. If I find time I'll look into the issue. Probably it will be automatically solved by the time the technical-refactor is done. 

My first guess would be that certain files need to be downloaded from iCloud before they show up in Jottre, and somehow block the main thread. (Causing UI lag)

Until the fix is deployed the easiest workaround would be to manually download the remote files using the integrated Files App:

`Files/iCloud Drive/Jottre`

https://user-images.githubusercontent.com/28454919/191230202-907b267e-940b-47ab-81dd-c35b57489726.MOV

**Comment by HerissonDigital** [comment]
Hi, I could finally solve it. Even though I thought I did so, it somehow worked now. The key issue is that, the boards should be downloaded in files app. I had removed it, to save space. So, as you suggested, it works now as before, with each board backing up to cloud but also there’s a folder under “On my iPad” That was the trick. 
thank you so much. Sorry for being able to look at it too late, so it stayed as a bug for long time. 🤗
Thank you again. 👍🏼
